export default function AuthConstants() {
  return {
    CHANGE_EVENT: 'AUTH_CHANGE_EVENT',
    REFRESH_CURRENT_USER: 'AUTH_REFRESH_CURRENT_USER',
    REFRESH_CURRENT_USERS: 'AUTH_REFRESH_CURRENT_USERS',
    FAILED_LOADING_USER: 'AUTH_FAILED_LOADING_USER',
    FAILED_LOADING_USERS: 'AUTH_FAILED_LOADING_USERS',
    FAILED_REGISTER: 'AUTH_FAILED_REGISTER',
    FAILED_LOGIN: 'AUTH_FAILED_LOGIN',
    FAILED_LOGOUT: 'AUTH_FAILED_LOGOUT'
  }
};
